
member:
  stage: build
  tags:
    - build
  # rules:
  #   - if: $CI_COMMIT_TAG
  # before_script:
  #   - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - npm -v
    - npm install